export default [
  'Stockholm',
  'Västra Götaland',
  'Östergötland',
  'Sörmland',
  'Örebro',
  'Uppsala',
  'Skåne',
  'Jönköping',
  'Dalarna',
  'Västmanland',
  'Blekinge',
  'Gotland',
  'Gävleborg',
  'Halland',
  'Jämtland Härjedalen',
  'Kalmar',
  'Kronoberg',
  'Norrbotten',
  'Värmland',
  'Västerbotten',
  'Västernorrland',
  'Sverige',
];
